### PR TITLE
[DISCUSS] Update mapping.json and populate.sh for ES 5.x

### PR DESCRIPTION
**Pull request by dakrone**
This updates the mapping and populate script for Elasticsearch 5.1.2. I have not
tested it against the contents of the book, but I have verified that the script
correctly runs.

### CODE REVIEW

**Comment by dakrone** [comment]
I opened this so we could have a discussion for how to handle 5.x.

Right now I'm thinking a separate branch, with a link in the README for users using 5.0+, what do you think @radu-gheorghe ?

**Comment by dakrone** [comment]
Another option is to maintain two different scripts and mappings in the same branch, like `mapping-5x.json` and `populate-5x.sh`, which would probably be a bit easier for newcomers.

**Comment by radu-gheorghe** [comment]
Thanks for working on this, @dakrone! Separate branch sounds like the best option to me, though I think the README should point that out. Let me know if you need any help.

**Comment by dbaranec** [comment]
it's working :) thx

**Comment by sbauer322** [comment]
The script runs fine for Elasticsearch v5.2.1 but I seem to be encountering some errors when testing it against the contents of Chapter 2.

Below are some curl commands with problems from the chapter and the result. Keep in mind, I do not know offhand if these results are expected... but there was no mention of expected failures with these curl commands in the chapter.

## Chapter 2

#### Changed

```
curl 'localhost:9200/get-together/group/_search?q=elasticsearch&fields=name,location&size=1&pretty'
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "The parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "The parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored"
  },
  "status" : 400
}
```

#### Broken?

```
curl 'localhost:9200/get-together/group/_search?pretty' -d '{  "query": {    "filtered": {      "filter": {        "term": {          "name": "elasticsearch"        }      }    }  }}'
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "no [query] registered for [filtered]",
        "line" : 1,
        "col" : 30
      }
    ],
    "type" : "parsing_exception",
    "reason" : "no [query] registered for [filtered]",
    "line" : 1,
    "col" : 30
  },
  "status" : 400
}
```

#### Broken?

```
curl localhost:9200/get-together/group/_search?pretty -d '{
  "aggregations" : {
    "organizers" : {
      "terms" : { "field" : "organizer" }
    }
  }
}'
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Fielddata is disabled on text fields by default. Set fielddata=true on [organizer] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "get-together",
        "node" : "FBhl6wGpRQKBJgxPjMq_Hw",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "Fielddata is disabled on text fields by default. Set fielddata=true on [organizer] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Fielddata is disabled on text fields by default. Set fielddata=true on [organizer] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
    }
  },
  "status" : 400
}
```

**Comment by radu-gheorghe** [comment]
Yes, those things have changed since we wrote the book, unfortunately. You can fix them like this:
1) use `_source` instead of `fields` to retrieve data from the `_source` field
2) use the `bool` instead of the `filtered` query, the rest should look the same
3) use `organizer.keyword` instead of `organizer` as the aggregation field. In 5.x, strings are autodetected as `text` (analyzed, for full-text search) and as `keyword` in the `keyword` subfield (like `organizer.keyword` here), which are not analyzed and can be used for exact matches, sorting and aggregations

**Comment by dakrone** [comment]
I merged this to the new 5.x branch in e1eb12918bdc4414e9ab1d650949208ac571a0d8 and updated the readme.

**Comment by sbauer322** [comment]
> Yes, those things have changed since we wrote the book, unfortunately.

Whoops, forgot to consider that as a possible reason. Thank you for the clarification, @radu-gheorghe!

**Comment by radu-gheorghe** [comment]
You're welcome @sbauer322

**Pull request closed without merging**
